import './globals.css'
import type { Metadata } from 'next'
import { Montserrat, Mulish } from 'next/font/google'

const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-montserrat' })
const mulish = Mulish({ subsets: ['latin'], variable: '--font-mulish' })

export const metadata: Metadata = {
  title: 'Windbnb',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${mulish.variable}`}>{children}</body>
    </html>
  )
}
